"use client";

import { Download } from "lucide-react";
import type { AssetDTO } from "@/contracts";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";

/**
 * How wide a generated asset renders. The reference measures ~425px at an 820px column; ours is a
 * fifth narrower by choice, so a turn's answer and its image both fit on screen together.
 */
const ASSET_WIDTH = 340;

/**
 * Generated outputs, rendered once after the prose.
 *
 * The reference briefly renders a generated image twice during terminal streaming — once from the
 * markdown link and once here — before settling on one. We render it once (UI-SPEC D-5).
 */
export function AssetStrip({ assets }: { assets: readonly AssetDTO[] }) {
  if (assets.length === 0) return null;

  return (
    <div className="mt-4 flex flex-col gap-3">
      {assets.map((asset) => (
        <Asset key={asset.url} asset={asset} />
      ))}
    </div>
  );
}

function Asset({ asset }: { asset: AssetDTO }) {
  if (asset.type === "video") {
    return (
      <video
        controls
        src={asset.url}
        style={{ maxWidth: ASSET_WIDTH }}
        className="w-full rounded-card border border-border bg-surface"
      />
    );
  }

  if (asset.type === "audio") {
    return <audio controls src={asset.url} style={{ maxWidth: ASSET_WIDTH }} className="w-full" />;
  }

  return (
    <div className="group/asset relative w-fit">
      <img
        src={asset.url}
        alt={asset.model ? `Generated by ${asset.model}` : "Generated image"}
        style={{ maxWidth: ASSET_WIDTH }}
        className="rounded-card bg-surface"
        loading="lazy"
      />
      <Tooltip>
        <TooltipTrigger
          asChild
          className="absolute top-2 right-2 rounded-md bg-black/60 p-1.5 text-white opacity-0 transition-opacity group-hover/asset:opacity-100 focus-visible:opacity-100"
        >
          <a href={asset.url} download aria-label="Download image">
            <Download className="size-4" aria-hidden />
          </a>
        </TooltipTrigger>
        <TooltipContent side="bottom">Download</TooltipContent>
      </Tooltip>
    </div>
  );
}
