"use client";

import { Download, Expand } from "lucide-react";
import type { AssetDTO } from "@/contracts";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { useUI } from "@/stores/ui";
import { FadeImage } from "@/components/FadeImage";

/**
 * How wide a generated asset renders. The reference measures ~425px at an 820px column; ours is a
 * fifth narrower by choice, so a turn's answer and its image both fit on screen together.
 */
const ASSET_WIDTH = 340;

/**
 * Generated outputs, rendered once after the prose.
 *
 * The reference briefly renders a generated image twice during terminal streaming — once from the
 * markdown link and once here — before settling on one. We render it once (UI-SPEC D-5).
 */
export function AssetStrip({ assets }: { assets: readonly AssetDTO[] }) {
  if (assets.length === 0) return null;

  return (
    <div className="mt-4 flex flex-col gap-3">
      {assets.map((asset) => (
        <Asset key={asset.url} asset={asset} />
      ))}
    </div>
  );
}

function Asset({ asset }: { asset: AssetDTO }) {
  if (asset.type === "video") {
    return (
      <video
        controls
        src={asset.url}
        style={{ maxWidth: ASSET_WIDTH }}
        className="w-full rounded-card border border-border bg-surface"
      />
    );
  }

  if (asset.type === "audio") {
    return <audio controls src={asset.url} style={{ maxWidth: ASSET_WIDTH }} className="w-full" />;
  }

  return <ImageAsset asset={asset} />;
}

/** Hover shows expand + download, the pair the reference shows; clicking the image opens the preview. */
function ImageAsset({ asset }: { asset: AssetDTO }) {
  const setPreviewFile = useUI((state) => state.setPreviewFile);

  return (
    <div className="group/asset relative w-fit">
      <button type="button" aria-label="Preview image" onClick={() => setPreviewFile(asset.url)}>
        <FadeImage
          src={asset.url}
          alt={asset.model ? `Generated by ${asset.model}` : "Generated image"}
          style={{ maxWidth: ASSET_WIDTH }}
          className="rounded-card bg-surface"
          loading="lazy"
        />
      </button>
      <div className="absolute top-2 right-2 flex gap-1 opacity-0 transition-opacity group-hover/asset:opacity-100 focus-within:opacity-100">
        <Tooltip>
          <TooltipTrigger
            type="button"
            aria-label="Expand image"
            onClick={() => setPreviewFile(asset.url)}
            className="rounded-md bg-black/60 p-1.5 text-white"
          >
            <Expand className="size-4" aria-hidden />
          </TooltipTrigger>
          <TooltipContent side="bottom">Expand</TooltipContent>
        </Tooltip>
        <Tooltip>
          <TooltipTrigger asChild className="rounded-md bg-black/60 p-1.5 text-white">
            <a href={asset.url} download aria-label="Download image" target="_blank" rel="noreferrer">
              <Download className="size-4" aria-hidden />
            </a>
          </TooltipTrigger>
          <TooltipContent side="bottom">Download</TooltipContent>
        </Tooltip>
      </div>
    </div>
  );
}
