// GENERATED by `pnpm sync-contracts` from magica-backend/src/contracts. Do not edit.
export * from "@/contracts/blocks";
export * from "@/contracts/messages";
export * from "@/contracts/api";
export * from "@/contracts/realtime";
