import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = join(root, "..", "magica-backend", "src", "contracts");
const target = join(root, "src", "contracts");

const BANNER = `// GENERATED by \`pnpm sync-contracts\` from magica-backend/src/contracts. Do not edit.\n`;

/**
 * Copies the backend's Zod contracts into this repo. The copy is committed — Vercel builds this
 * repo alone, so an uncommitted `contracts/` fails at import time.
 *
 * INVARIANT: `--check` can only compare when the backend is on disk, so on Vercel it proves
 * NOTHING. It says so loudly rather than passing quietly — a silent skip is how a missing
 * `failureCode` shipped for four days while every build stayed green. The gate that actually
 * covers a deploy is CI with both repositories checked out.
 */
function syncContracts(): void {
  const check = process.argv.includes("--check");

  if (!existsSync(source)) {
    if (check) {
      console.warn(
        `\nsync-contracts: NOT CHECKED — no backend at ${source}.\n` +
          "  This build cannot tell whether src/contracts/ still matches the backend.\n" +
          "  Drift ships silently from here. Run the check beside a magica-backend checkout,\n" +
          "  or in CI with both repositories present.\n",
      );
      return;
    }

    console.warn(`sync-contracts: no backend at ${source} — nothing copied.`);
    return;
  }

  mkdirSync(target, { recursive: true });
  const files = readdirSync(source).filter((f) => f.endsWith(".ts"));
  const drifted: string[] = [];

  for (const file of files) {
    const expected = BANNER + readFileSync(join(source, file), "utf8");
    const path = join(target, file);
    const actual = existsSync(path) ? readFileSync(path, "utf8") : null;

    if (actual === expected) continue;
    if (check) drifted.push(file);
    else writeFileSync(path, expected);
  }

  const stale = existsSync(target)
    ? readdirSync(target).filter((f) => f.endsWith(".ts") && !files.includes(f))
    : [];

  if (check) {
    if (drifted.length === 0 && stale.length === 0) {
      console.log(`sync-contracts: ${files.length} files in sync.`);
      return;
    }
    console.error("sync-contracts: contracts have DRIFTED from the backend.");
    for (const f of drifted) console.error(`  changed: ${f}`);
    for (const f of stale) console.error(`  removed upstream: ${f}`);
    console.error("Run `pnpm sync-contracts` and commit the result.");
    process.exit(1);
  }

  for (const f of stale) console.warn(`sync-contracts: ${f} no longer exists upstream — delete it.`);
  console.log(`sync-contracts: wrote ${files.length} files to src/contracts.`);
}

syncContracts();
